/* WARNING: This file has been autogenerated. Do not modify it directly! */

#include <XM/xMirror.hpp>

using namespace std;
using namespace xm;

Method::Method
(
    const string& uName,
    const Type& retType,
    const Class& owner,
    const Type& paramType0,
    const Type& paramType1,
    const Type& paramType2,
    const Type& paramType3,
    const Type& paramType4,
    const Type& paramType5,
    const Type& paramType6
) :
    Item(uName, owner),
    Function
    (
        uName,
        retType,
        owner,
        paramType0,
        paramType1,
        paramType2,
        paramType3,
        paramType4,
        paramType5,
        paramType6
    )
{
}
