/* WARNING: This file has been autogenerated. Do not modify it directly! */

#ifndef XM_PARAMLISTS_HPP
#define XM_PARAMLISTS_HPP

#define _XM_FUNCTION_CONSTRUCTOR_PARAMS \
const Type& paramType0 = getType<void>(), \
const Type& paramType1 = getType<void>(), \
const Type& paramType2 = getType<void>(), \
const Type& paramType3 = getType<void>(), \
const Type& paramType4 = getType<void>(), \
const Type& paramType5 = getType<void>(), \
const Type& paramType6 = getType<void>(), \
const Type& paramType7 = getType<void>()

#define _XM_FUNCTION_CALL_PARAMS \
const Variant& arg0 = Variant::Void, \
const Variant& arg1 = Variant::Void, \
const Variant& arg2 = Variant::Void, \
const Variant& arg3 = Variant::Void, \
const Variant& arg4 = Variant::Void, \
const Variant& arg5 = Variant::Void, \
const Variant& arg6 = Variant::Void, \
const Variant& arg7 = Variant::Void

#define _XM_FUNCTION_CALLIMPL_PARAMS \
Variant& arg0, \
Variant& arg1, \
Variant& arg2, \
Variant& arg3, \
Variant& arg4, \
Variant& arg5, \
Variant& arg6, \
Variant& arg7

#define _XM_METHOD_CONSTRUCTOR_PARAMS \
const Type& paramType0 = getType<void>(), \
const Type& paramType1 = getType<void>(), \
const Type& paramType2 = getType<void>(), \
const Type& paramType3 = getType<void>(), \
const Type& paramType4 = getType<void>(), \
const Type& paramType5 = getType<void>(), \
const Type& paramType6 = getType<void>()

#define _XM_METHOD_CALL_PARAMS \
const Variant& arg0 = Variant::Void, \
const Variant& arg1 = Variant::Void, \
const Variant& arg2 = Variant::Void, \
const Variant& arg3 = Variant::Void, \
const Variant& arg4 = Variant::Void, \
const Variant& arg5 = Variant::Void, \
const Variant& arg6 = Variant::Void

#endif /*XM_PARAMLISTS_HPP*/

